/**
 * Vercel Edge Middleware (Epic 3 — Directory & LLM/Search Discoverability).
 *
 * Intercepts /:clientSlug/:mapSlug/directory[/:listingSlug] and serves the
 * pre-generated static HTML (or sitemap.xml) directly from Vercel Blob,
 * before the request reaches vercel.json's SPA rewrite to index.html.
 * Every other path falls through unchanged — this middleware only ever
 * returns a Response for paths shaped exactly like the above; anything
 * else (including a wrong/unpublished/unentitled slug combination, where
 * no blob exists) falls through to the normal SPA behaviour.
 *
 * Content is generated by the generate_directory_pages Supabase Edge
 * Function (fires on publish + nightly cron) and uploaded to the same
 * Vercel Blob store the existing map snapshot feature already uses —
 * VITE_SNAPSHOT_BASE_URL (already configured in the Vercel project for the
 * Vite build) is reused here as the blob store's public base URL.
 */

export const config = {
  matcher: "/((?!assets/|favicon|robots.txt).*)",
};

export default async function middleware(request) {
  const url = new URL(request.url);
  const segments = url.pathname.split("/").filter(Boolean);

  // Expect exactly /:clientSlug/:mapSlug/directory[/:listingSlug] — anything
  // else (including the plain /:clientSlug/:mapSlug interactive map route)
  // is not ours; return nothing so Vercel continues its normal routing.
  if (segments.length < 3 || segments.length > 4 || segments[2] !== "directory") {
    return;
  }

  const [clientSlug, mapSlug] = segments;
  const listingSlug = segments[3];

  const blobBase = process.env.VITE_SNAPSHOT_BASE_URL;
  if (!blobBase) return; // misconfigured — fail open to the normal SPA route rather than break the site

  let pathname;
  let contentType;
  if (!listingSlug) {
    pathname = `directory/${clientSlug}/${mapSlug}/index.html`;
    contentType = "text/html; charset=utf-8";
  } else if (listingSlug === "sitemap.xml") {
    pathname = `directory/${clientSlug}/${mapSlug}/sitemap.xml`;
    contentType = "application/xml; charset=utf-8";
  } else {
    pathname = `directory/${clientSlug}/${mapSlug}/${listingSlug}.html`;
    contentType = "text/html; charset=utf-8";
  }

  let upstream;
  try {
    upstream = await fetch(`${blobBase}/${pathname}`);
  } catch {
    return; // network error reaching blob storage — fail open
  }
  if (!upstream.ok) return; // nothing generated at this path — fall through to the SPA

  const html = await upstream.text();
  return new Response(html, {
    status: 200,
    headers: { "content-type": contentType },
  });
}
