/**
 * Vercel Edge Middleware (Epic 3 — Directory & LLM/Search Discoverability;
 * extended in Epic 4 — Bring Your Own Domain, Phase 2).
 *
 * Two responsibilities, branched on the request's Host header:
 *
 * 1. Branded domain (maps.layercake-cx.biz, Vercel previews) — unchanged
 *    since Epic 3: intercepts /:clientSlug/:mapSlug/directory[/:listingSlug]
 *    and serves the pre-generated static HTML (or sitemap.xml) directly from
 *    Vercel Blob, before the request reaches vercel.json's SPA rewrite to
 *    index.html. Every other path falls through unchanged.
 *
 * 2. Custom domain (a client's own verified domain, client_domains.status =
 *    'active') — resolves which client/map that hostname publishes via a
 *    Supabase REST lookup, then serves the same pre-generated content at
 *    the decided URL scheme: `/` → directory landing, `/:listingSlug` →
 *    listing page, `/map` → falls through to the SPA (a client-side route
 *    resolves the map by hostname itself; see CustomDomainMap.jsx). Domains
 *    that don't resolve, or aren't active yet, get an honest static
 *    response rather than silently falling into the branded domain's own
 *    route table (which would show the wrong content).
 *
 * Content is generated by the generate_directory_pages Supabase Edge
 * Function (fires on publish + nightly cron) and uploaded to the same
 * Vercel Blob store the existing map snapshot feature already uses —
 * VITE_SNAPSHOT_BASE_URL (already configured in the Vercel project for the
 * Vite build) is reused here as the blob store's public base URL.
 *
 * Known limitation: a listing whose own slug happens to be exactly "map"
 * is unreachable at the custom-domain root (`/map` is reserved for the
 * interactive map route). Accepted as a negligible edge case rather than
 * adding path-collision handling for it.
 */

export const config = {
  matcher: "/((?!assets/|favicon|robots.txt).*)",
};

const BRANDED_HOST = process.env.VITE_BRANDED_HOST || "maps.layercake-cx.biz";

function isBrandedHost(host) {
  return host === BRANDED_HOST || host.endsWith(".vercel.app") || host === "localhost";
}

function htmlResponse(status, title, body) {
  return new Response(
    `<!doctype html><html><body style="font-family:sans-serif;padding:60px;text-align:center;color:#444"><h1>${title}</h1><p>${body}</p></body></html>`,
    { status, headers: { "content-type": "text/html; charset=utf-8" } },
  );
}

async function fetchBlobHtml(blobBase, pathname) {
  try {
    const upstream = await fetch(`${blobBase}/${pathname}`);
    if (!upstream.ok) return null;
    return await upstream.text();
  } catch {
    return null;
  }
}

/**
 * Resolves a hostname to the client/map slugs it publishes, via the
 * resolve_custom_domain() RPC — deliberately not a raw select against
 * client_domains with an embedded clients(slug)/maps(slug) join: the
 * clients table has no anon-select policy (it carries columns, like
 * plan_key and email_domain_status, that maps/groups/listings never had
 * when their anon-read policies were written), so the embed would just
 * return null for clients. The RPC is security definer and returns only
 * the two slugs + status, nothing else. Null return means not found.
 */
async function resolveCustomDomain(host) {
  const supabaseUrl = process.env.VITE_SUPABASE_URL;
  const anonKey = process.env.VITE_SUPABASE_ANON_KEY;
  if (!supabaseUrl || !anonKey) return null;

  try {
    const res = await fetch(`${supabaseUrl}/rest/v1/rpc/resolve_custom_domain`, {
      method: "POST",
      headers: {
        apikey: anonKey,
        Authorization: `Bearer ${anonKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ p_hostname: host }),
    });
    if (!res.ok) return null;
    const rows = await res.json();
    const row = Array.isArray(rows) ? rows[0] : null;
    if (!row) return null;
    return { status: row.status, clientSlug: row.client_slug, mapSlug: row.map_slug };
  } catch {
    return null;
  }
}

async function handleCustomDomain(host, segments, blobBase) {
  const domain = await resolveCustomDomain(host);
  if (!domain) {
    return htmlResponse(404, "Domain not configured", "This domain isn&apos;t connected to a Layercake Maps directory.");
  }
  if (domain.status !== "active") {
    return htmlResponse(200, "This domain is being verified", "DNS setup is still in progress. Check back soon.");
  }

  // /map and /embed — the live interactive SPA. Fall through to index.html.
  // /map's client-side route resolves client/map by hostname itself; /embed
  // is the pre-existing query-param-driven route, also used by the
  // directory landing page's own embedded iframe (src="/embed?map=...").
  if (segments.length === 1 && (segments[0] === "map" || segments[0] === "embed")) return;

  if (!domain.clientSlug || !domain.mapSlug || !blobBase) {
    return htmlResponse(404, "Domain not configured", "This domain isn&apos;t connected to a Layercake Maps directory.");
  }

  let pathname;
  let contentType = "text/html; charset=utf-8";
  if (segments.length === 0) {
    pathname = `directory/${domain.clientSlug}/${domain.mapSlug}/index.html`;
  } else if (segments.length === 1 && segments[0] === "sitemap.xml") {
    pathname = `directory/${domain.clientSlug}/${domain.mapSlug}/sitemap.xml`;
    contentType = "application/xml; charset=utf-8";
  } else if (segments.length === 1) {
    pathname = `directory/${domain.clientSlug}/${domain.mapSlug}/${segments[0]}.html`;
  } else {
    return htmlResponse(404, "Not found", "Nothing here.");
  }

  const html = await fetchBlobHtml(blobBase, pathname);
  if (html == null) {
    return contentType.includes("xml")
      ? new Response("", { status: 404 })
      : htmlResponse(200, "Not published yet", "This directory hasn&apos;t been published.");
  }
  return new Response(rewriteForCustomDomain(html, host, domain), {
    status: 200,
    headers: { "content-type": contentType },
  });
}

/**
 * generate_directory_pages (Epic 3) bakes links/canonical/JSON-LD as
 * absolute paths rooted at the BRANDED domain's own URL shape
 * (/:clientSlug/:mapSlug/directory[/:listingSlug] — where that content
 * normally lives). Serving the exact same static content at a custom
 * domain's root needs those rewritten to the custom domain's own shape
 * (/ for the directory root, /:listingSlug for a listing, /map for the
 * interactive map) — otherwise every internal link and the canonical URL
 * point at a path structure that doesn't exist on the custom domain at
 * all. Real per-domain content generation (Phase 3) would be the more
 * thorough fix; this is a serve-time rewrite of the one shared static
 * asset, scoped tightly enough (quote/tag-bounded patterns) that it can't
 * touch unrelated content like a listing's own external website link.
 */
function rewriteForCustomDomain(text, host, { clientSlug, mapSlug }) {
  const brandedDirBase = `https://maps.layercake-cx.biz/${clientSlug}/${mapSlug}/directory`;
  const rootRelativeDirBase = `/${clientSlug}/${mapSlug}/directory`;
  const brandedMapUrl = `https://maps.layercake-cx.biz/${clientSlug}/${mapSlug}`;
  const rootRelativeMapUrl = `/${clientSlug}/${mapSlug}`;
  const customOrigin = `https://${host}`;

  let out = text;
  out = out.split(`${brandedDirBase}/`).join(`${customOrigin}/`);
  out = out.split(brandedDirBase).join(customOrigin);
  out = out.split(`${rootRelativeDirBase}/`).join("/");
  out = out.split(rootRelativeDirBase).join("/");
  out = out.split(`${brandedMapUrl}"`).join(`${customOrigin}/map"`);
  out = out.split(`${rootRelativeMapUrl}"`).join(`/map"`);
  return out;
}

export default async function middleware(request) {
  const url = new URL(request.url);
  const segments = url.pathname.split("/").filter(Boolean);
  const blobBase = process.env.VITE_SNAPSHOT_BASE_URL;

  if (!isBrandedHost(url.hostname)) {
    return handleCustomDomain(url.hostname, segments, blobBase);
  }

  // Branded domain — unchanged since Epic 3. Expect exactly
  // /:clientSlug/:mapSlug/directory[/:listingSlug] — anything else
  // (including the plain /:clientSlug/:mapSlug interactive map route) is
  // not ours; return nothing so Vercel continues its normal routing.
  if (segments.length < 3 || segments.length > 4 || segments[2] !== "directory") {
    return;
  }

  const [clientSlug, mapSlug] = segments;
  const listingSlug = segments[3];
  if (!blobBase) return; // misconfigured — fail open to the normal SPA route rather than break the site

  let pathname;
  let contentType;
  if (!listingSlug) {
    pathname = `directory/${clientSlug}/${mapSlug}/index.html`;
    contentType = "text/html; charset=utf-8";
  } else if (listingSlug === "sitemap.xml") {
    pathname = `directory/${clientSlug}/${mapSlug}/sitemap.xml`;
    contentType = "application/xml; charset=utf-8";
  } else {
    pathname = `directory/${clientSlug}/${mapSlug}/${listingSlug}.html`;
    contentType = "text/html; charset=utf-8";
  }

  const html = await fetchBlobHtml(blobBase, pathname);
  if (html == null) return; // nothing generated at this path — fall through to the SPA
  return new Response(html, { status: 200, headers: { "content-type": contentType } });
}
