/**
 * Vercel Edge Middleware (Epic 3 — Directory & LLM/Search Discoverability;
 * extended in Epic 4 — Bring Your Own Domain, Phase 2; extended again in
 * the Directories build-out, Phase 3b, for the separate Directory entity).
 *
 * Three responsibilities, branched on the request's Host header and path:
 *
 * 1. Branded domain, Directory-entity pages (new, Phase 3b): intercepts
 *    /directories/:clientSlug/:directorySlug[/:entrySlug] and serves
 *    generate_directory_site's static output. The literal "directories"
 *    (plural) first segment is deliberate — it's the ONLY way to route a
 *    Directory's own homepage without an ambiguity-resolving DB lookup on
 *    every request: a bare /:clientSlug/:directorySlug would be
 *    byte-identical in shape to the existing /:clientSlug/:mapSlug
 *    interactive-map route (exactly 2 segments, client-side routed via
 *    SlugMap.jsx/get_map_id_by_slugs), and paying a lookup cost on every
 *    map page load to disambiguate was rejected as a real regression to a
 *    live feature. Checked first, before anything else, and returns
 *    immediately either way — it can never fall into or be shadowed by the
 *    branches below.
 *
 * 2. Branded domain, Map's own directory pages (Epic 3 — unrelated entity,
 *    confusingly similar name; see generate_directory_pages' own header
 *    comment) — unchanged since Epic 3: intercepts
 *    /:clientSlug/:mapSlug/directory[/:listingSlug] and serves that
 *    pre-generated static HTML (or sitemap.xml) directly from Vercel Blob,
 *    before the request reaches vercel.json's SPA rewrite to index.html.
 *    Every other branded-domain path (including the plain interactive map
 *    route) falls through unchanged, exactly as before Phase 3b.
 *
 * 3. Custom domain (a client's own verified domain, client_domains.status =
 *    'active') — resolves which client/map that hostname publishes via a
 *    Supabase REST lookup, then serves the same pre-generated content at
 *    the decided URL scheme: `/` → directory landing, `/:listingSlug` →
 *    listing page, `/map` → falls through to the SPA (a client-side route
 *    resolves the map by hostname itself; see CustomDomainMap.jsx). Domains
 *    that don't resolve, or aren't active yet, get an honest static
 *    response rather than silently falling into the branded domain's own
 *    route table (which would show the wrong content). Directory-entity
 *    custom domains are not built yet (planned for DIR-E3/Phase 4,
 *    alongside generalizing client_domains/resolve_custom_domain to be
 *    entity-polymorphic) — a custom domain can only ever resolve to a map
 *    today.
 *
 * Content for (1) is generated by the generate_directory_site Supabase Edge
 * Function; content for (2)/(3) by generate_directory_pages. Both upload to
 * the same Vercel Blob store the existing map snapshot feature already
 * uses, at deliberately distinct top-level path prefixes ("directories/"
 * vs "directory/") so the two can never collide even if a client's map slug
 * and directory slug happen to match. VITE_SNAPSHOT_BASE_URL (already
 * configured in the Vercel project for the Vite build) is reused here as
 * the blob store's public base URL.
 *
 * Known limitation: a listing whose own slug happens to be exactly "map"
 * is unreachable at the custom-domain root (`/map` is reserved for the
 * interactive map route). Accepted as a negligible edge case rather than
 * adding path-collision handling for it.
 */

export const config = {
  matcher: "/((?!assets/|favicon|robots.txt).*)",
};

const BRANDED_HOST = process.env.VITE_BRANDED_HOST || "maps.layercake-cx.biz";

function isBrandedHost(host) {
  return host === BRANDED_HOST || host.endsWith(".vercel.app") || host === "localhost";
}

function htmlResponse(status, title, body) {
  return new Response(
    `<!doctype html><html><body style="font-family:sans-serif;padding:60px;text-align:center;color:#444"><h1>${title}</h1><p>${body}</p></body></html>`,
    { status, headers: { "content-type": "text/html; charset=utf-8" } },
  );
}

async function fetchBlobHtml(blobBase, pathname) {
  try {
    const upstream = await fetch(`${blobBase}/${pathname}`);
    if (!upstream.ok) return null;
    return await upstream.text();
  } catch {
    return null;
  }
}

/**
 * Resolves a hostname to the client + (map or directory) it publishes, via
 * the resolve_custom_domain() RPC — deliberately not a raw select against
 * client_domains with an embedded clients(slug)/maps(slug)/directories(slug)
 * join: the clients table has no anon-select policy (it carries columns,
 * like plan_key and email_domain_status, that maps/groups/listings never
 * had when their anon-read policies were written), so the embed would just
 * return null for clients. The RPC is security definer and returns only
 * entity_type + the two slugs + status, nothing else. Null return means
 * not found.
 *
 * entity_type/entity_slug replaced the original map-only (client_slug,
 * map_slug, status) shape in 20260827130000 — this function's contract
 * with callers (below) is the only thing that changed; the request itself
 * still costs exactly one round-trip, same as before.
 */
async function resolveCustomDomain(host) {
  const supabaseUrl = process.env.VITE_SUPABASE_URL;
  const anonKey = process.env.VITE_SUPABASE_ANON_KEY;
  if (!supabaseUrl || !anonKey) return null;

  try {
    const res = await fetch(`${supabaseUrl}/rest/v1/rpc/resolve_custom_domain`, {
      method: "POST",
      headers: {
        apikey: anonKey,
        Authorization: `Bearer ${anonKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ p_hostname: host }),
    });
    if (!res.ok) return null;
    const rows = await res.json();
    const row = Array.isArray(rows) ? rows[0] : null;
    if (!row) return null;
    // Tolerate the pre-20260827130000 (map-only) return shape too — a DB
    // migration and a Vercel deploy are two independent operations with no
    // atomic joint release, so there's a real window where this code can
    // run against either the old or new RPC shape regardless of deploy
    // order. Detected by the new entity_type column's presence, not a
    // version flag, since the RPC itself carries no version marker.
    if ("entity_type" in row) {
      return { status: row.status, entityType: row.entity_type, clientSlug: row.client_slug, entitySlug: row.entity_slug };
    }
    return { status: row.status, entityType: "map", clientSlug: row.client_slug, entitySlug: row.map_slug };
  } catch {
    return null;
  }
}

async function handleCustomDomain(host, segments, blobBase) {
  const domain = await resolveCustomDomain(host);
  if (!domain) {
    return htmlResponse(404, "Domain not configured", "This domain isn&apos;t connected to a Layercake Maps directory.");
  }
  if (domain.status !== "active") {
    return htmlResponse(200, "This domain is being verified", "DNS setup is still in progress. Check back soon.");
  }

  // /map and /embed — the live interactive SPA, map-hosted domains only.
  // /map's client-side route resolves client/map by hostname itself; /embed
  // is the pre-existing query-param-driven route, also used by the
  // directory landing page's own embedded iframe (src="/embed?map=...").
  // These two segments just fall through to the SPA's own not-found
  // handling for that case, same as any other unmatched path.
  if (domain.entityType === "map" && segments.length === 1 && (segments[0] === "map" || segments[0] === "embed")) return;

  // /directory-embed — the directory homepage's own pins-only map iframe
  // (src="/directory-embed?..."), same pattern as /embed above. Without
  // this, a directory custom domain would treat "directory-embed" as an
  // unrecognised entry slug and serve a 404-ish blob lookup instead of
  // falling through to the SPA.
  if (domain.entityType === "directory" && segments.length === 1 && segments[0] === "directory-embed") return;

  if (!domain.clientSlug || !domain.entitySlug || !blobBase) {
    return htmlResponse(404, "Domain not configured", "This domain isn&apos;t connected to a Layercake Maps directory.");
  }

  // Same "directory/" (map) vs "directories/" (directory entity) Blob path
  // split as the branded-domain routes above — see this file's header
  // comment and generate_directory_site's own header comment for why.
  const basePath =
    domain.entityType === "directory"
      ? `directories/${domain.clientSlug}/${domain.entitySlug}`
      : `directory/${domain.clientSlug}/${domain.entitySlug}`;

  let pathname;
  let contentType = "text/html; charset=utf-8";
  if (segments.length === 0) {
    pathname = `${basePath}/index.html`;
  } else if (segments.length === 1 && segments[0] === "sitemap.xml") {
    pathname = `${basePath}/sitemap.xml`;
    contentType = "application/xml; charset=utf-8";
  } else if (domain.entityType === "directory" && segments.length === 1 && segments[0] === "llms.txt") {
    pathname = `${basePath}/llms.txt`;
    contentType = "text/plain; charset=utf-8";
  } else if (segments.length === 1) {
    pathname = `${basePath}/${segments[0]}.html`;
  } else {
    return htmlResponse(404, "Not found", "Nothing here.");
  }

  const html = await fetchBlobHtml(blobBase, pathname);
  if (html == null) {
    if (contentType.includes("xml") || contentType.includes("text/plain")) return new Response("", { status: 404 });

    // Directory entries can be renamed — check the redirect manifest before
    // giving up, same mechanism as the branded-domain directory routes.
    if (domain.entityType === "directory" && segments.length === 1 && segments[0] !== "sitemap.xml" && segments[0] !== "llms.txt") {
      const redirectsJson = await fetchBlobHtml(blobBase, `${basePath}/redirects.json`);
      if (redirectsJson != null) {
        try {
          const redirects = JSON.parse(redirectsJson);
          const newSlug = redirects[segments[0]];
          if (newSlug) return new Response(null, { status: 301, headers: { location: `/${newSlug}` } });
        } catch {
          // malformed manifest — fall through to the "not published" response below
        }
      }
    }

    return htmlResponse(200, "Not published yet", "This directory hasn&apos;t been published.");
  }
  return new Response(rewriteForCustomDomain(html, host, domain), {
    status: 200,
    headers: { "content-type": contentType },
  });
}

/**
 * generate_directory_pages (map entity) and generate_directory_site
 * (directory entity) both bake links/canonical/JSON-LD as absolute paths
 * rooted at the BRANDED domain's own URL shape — /:clientSlug/:mapSlug/
 * directory[/:listingSlug] for maps, /directories/:clientSlug/:directorySlug
 * [/:entrySlug] for directories (see each function's own header comment).
 * Serving the exact same static content at a custom domain's root needs
 * those rewritten to the custom domain's own shape (/ for the root,
 * /:slug for an entry/listing, plus /map for a map's interactive embed —
 * directories have no such embed yet) — otherwise every internal link and
 * the canonical URL point at a path structure that doesn't exist on the
 * custom domain at all. Real per-domain content generation would be the
 * more thorough fix; this is a serve-time rewrite of the one shared static
 * asset, scoped tightly enough (quote/tag-bounded patterns) that it can't
 * touch unrelated content like an entry's own external website link.
 */
function rewriteForCustomDomain(text, host, { entityType, clientSlug, entitySlug }) {
  const brandedBase =
    entityType === "directory"
      ? `https://maps.layercake-cx.biz/directories/${clientSlug}/${entitySlug}`
      : `https://maps.layercake-cx.biz/${clientSlug}/${entitySlug}/directory`;
  const rootRelativeBase =
    entityType === "directory" ? `/directories/${clientSlug}/${entitySlug}` : `/${clientSlug}/${entitySlug}/directory`;
  const customOrigin = `https://${host}`;

  let out = text;
  out = out.split(`${brandedBase}/`).join(`${customOrigin}/`);
  out = out.split(brandedBase).join(customOrigin);
  out = out.split(`${rootRelativeBase}/`).join("/");
  out = out.split(rootRelativeBase).join("/");

  if (entityType !== "directory") {
    const brandedMapUrl = `https://maps.layercake-cx.biz/${clientSlug}/${entitySlug}`;
    const rootRelativeMapUrl = `/${clientSlug}/${entitySlug}`;
    out = out.split(`${brandedMapUrl}"`).join(`${customOrigin}/map"`);
    out = out.split(`${rootRelativeMapUrl}"`).join(`/map"`);
  }

  return out;
}

/**
 * Directory entity's own static pages on the branded domain — Phase 3b.
 * segments[0] === "directories" already confirmed by the caller.
 */
async function handleDirectorySite(segments, blobBase) {
  const clientSlug = segments[1];
  const directorySlug = segments[2];
  const entrySlug = segments[3];

  // Malformed (missing slugs) or more than 4 segments (nothing generated
  // this deep) — not ours, fall through to the SPA rather than 404 outright.
  if (!clientSlug || !directorySlug || segments.length > 4) return;
  if (!blobBase) return; // misconfigured — fail open to the normal SPA route rather than break the site

  const base = `directories/${clientSlug}/${directorySlug}`;

  let pathname;
  let contentType;
  if (!entrySlug) {
    pathname = `${base}/index.html`;
    contentType = "text/html; charset=utf-8";
  } else if (entrySlug === "sitemap.xml") {
    pathname = `${base}/sitemap.xml`;
    contentType = "application/xml; charset=utf-8";
  } else if (entrySlug === "llms.txt") {
    pathname = `${base}/llms.txt`;
    contentType = "text/plain; charset=utf-8";
  } else {
    pathname = `${base}/${entrySlug}.html`;
    contentType = "text/html; charset=utf-8";
  }

  const html = await fetchBlobHtml(blobBase, pathname);
  if (html != null) return new Response(html, { status: 200, headers: { "content-type": contentType } });

  // Only a plain entry-slug lookup can be a stale/renamed URL — the
  // directory landing page, sitemap.xml and llms.txt are never redirect
  // targets. Check the pre-generated redirect manifest (docs/DIRECTORIES.md
  // §5.11) before giving up and falling through to the SPA.
  if (entrySlug && entrySlug !== "sitemap.xml" && entrySlug !== "llms.txt") {
    const redirectsJson = await fetchBlobHtml(blobBase, `${base}/redirects.json`);
    if (redirectsJson != null) {
      try {
        const redirects = JSON.parse(redirectsJson);
        const newSlug = redirects[entrySlug];
        if (newSlug) {
          return new Response(null, {
            status: 301,
            headers: { location: `/directories/${clientSlug}/${directorySlug}/${newSlug}` },
          });
        }
      } catch {
        // malformed manifest — fall through to the SPA rather than error
      }
    }
  }

  return; // nothing generated at this path and no redirect found — fall through to the SPA, same convention as the map branch below
}

export default async function middleware(request) {
  const url = new URL(request.url);
  const segments = url.pathname.split("/").filter(Boolean);
  const blobBase = process.env.VITE_SNAPSHOT_BASE_URL;

  if (!isBrandedHost(url.hostname)) {
    return handleCustomDomain(url.hostname, segments, blobBase);
  }

  // Directory entity pages — checked first; see the file-level comment for
  // why the literal "directories" segment is what makes this collision-free
  // against the map interactive route without a lookup.
  if (segments[0] === "directories") {
    return handleDirectorySite(segments, blobBase);
  }

  // Branded domain — unchanged since Epic 3. Expect exactly
  // /:clientSlug/:mapSlug/directory[/:listingSlug] — anything else
  // (including the plain /:clientSlug/:mapSlug interactive map route) is
  // not ours; return nothing so Vercel continues its normal routing.
  if (segments.length < 3 || segments.length > 4 || segments[2] !== "directory") {
    return;
  }

  const [clientSlug, mapSlug] = segments;
  const listingSlug = segments[3];
  if (!blobBase) return; // misconfigured — fail open to the normal SPA route rather than break the site

  let pathname;
  let contentType;
  if (!listingSlug) {
    pathname = `directory/${clientSlug}/${mapSlug}/index.html`;
    contentType = "text/html; charset=utf-8";
  } else if (listingSlug === "sitemap.xml") {
    pathname = `directory/${clientSlug}/${mapSlug}/sitemap.xml`;
    contentType = "application/xml; charset=utf-8";
  } else {
    pathname = `directory/${clientSlug}/${mapSlug}/${listingSlug}.html`;
    contentType = "text/html; charset=utf-8";
  }

  const html = await fetchBlobHtml(blobBase, pathname);
  if (html == null) return; // nothing generated at this path — fall through to the SPA
  return new Response(html, { status: 200, headers: { "content-type": contentType } });
}
