-- Tenant-scoped RLS policies.
--
-- Replaces the overly-broad `using (true)` policies that allowed any authenticated
-- user to read and write every other client's data.
--
-- After this migration:
--   • admin users  → full access to all tables (unchanged)
--   • client users → scoped to their own organisation only
--   • anon         → read-only embed access unchanged (maps/groups/listings)
--
-- Three edge-case flows that insert across tenants are handled explicitly:
--   1. New-user signup   → provisionClientSignup inserts client + contact
--   2. Invitation accept → acceptPendingInvitation inserts contact + map perms
--   3. Embed contact form → anon inserts map_contact_submissions
--
-- Tables covered: clients, maps, groups, listings, contacts, map_data_sources,
--                 invitations, contact_map_permissions, map_publications,
--                 map_contact_submissions, profiles.
--
-- Security-definer functions covered: publish_map, rollback_map_to,
--                                     list_map_publications.

-- ============================================================
-- STEP 0: Helper function
-- security definer so it can read contacts without triggering
-- the contacts table's own RLS policy (avoids circular deps).
-- ============================================================

create or replace function public.current_user_client_id()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select client_id from public.contacts where user_id = auth.uid() limit 1;
$$;

revoke all on function public.current_user_client_id() from public;
grant execute on function public.current_user_client_id() to authenticated;


-- ============================================================
-- STEP 1: PROFILES
-- Existing: profiles_select_own (users see their own row only)
-- Add:      admins can see all profiles (for admin panel)
-- ============================================================

-- Guard: only create if it doesn't exist yet (idempotent).
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'profiles'
      and policyname = 'profiles_admin_select'
  ) then
    execute $pol$
      create policy "profiles_admin_select"
        on public.profiles for select
        to authenticated
        using (
          exists (
            select 1 from public.profiles p
            where p.user_id = auth.uid() and p.role = 'admin'
          )
        )
    $pol$;
  end if;
end;
$$;


-- ============================================================
-- STEP 2: CLIENTS
-- ============================================================

drop policy if exists "clients_authenticated_all" on public.clients;

-- Admins: full access to all client rows
create policy "clients_admin_all"
  on public.clients for all
  to authenticated
  using (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  );

-- Users: read their own organisation only
create policy "clients_own_select"
  on public.clients for select
  to authenticated
  using (id = public.current_user_client_id());

-- Users: update their own organisation only
create policy "clients_own_update"
  on public.clients for update
  to authenticated
  using  (id = public.current_user_client_id())
  with check (id = public.current_user_client_id());

-- New-user signup: provisionClientSignup creates a client before the contact
-- row exists, so current_user_client_id() returns null at that moment.
-- Insert is still safe because the client id is a fresh UUID generated by the caller.
create policy "clients_insert_on_signup"
  on public.clients for insert
  to authenticated
  with check (true);


-- ============================================================
-- STEP 3: MAPS
-- Keep: maps_anon_select (embed needs to load map config)
-- ============================================================

drop policy if exists "maps_authenticated_all" on public.maps;

create policy "maps_admin_all"
  on public.maps for all
  to authenticated
  using (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  );

create policy "maps_own_client"
  on public.maps for all
  to authenticated
  using  (client_id = public.current_user_client_id())
  with check (client_id = public.current_user_client_id());


-- ============================================================
-- STEP 4: GROUPS
-- Keep: groups_anon_select (embed loads group labels/colours)
-- ============================================================

drop policy if exists "groups_authenticated_all" on public.groups;

create policy "groups_admin_all"
  on public.groups for all
  to authenticated
  using (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  );

create policy "groups_own_client"
  on public.groups for all
  to authenticated
  using (
    map_id in (
      select id from public.maps where client_id = public.current_user_client_id()
    )
  )
  with check (
    map_id in (
      select id from public.maps where client_id = public.current_user_client_id()
    )
  );


-- ============================================================
-- STEP 5: LISTINGS
-- Keep: listings_anon_select (embed loads pins)
-- ============================================================

drop policy if exists "listings_authenticated_all" on public.listings;

create policy "listings_admin_all"
  on public.listings for all
  to authenticated
  using (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  );

create policy "listings_own_client"
  on public.listings for all
  to authenticated
  using (
    map_id in (
      select id from public.maps where client_id = public.current_user_client_id()
    )
  )
  with check (
    map_id in (
      select id from public.maps where client_id = public.current_user_client_id()
    )
  );


-- ============================================================
-- STEP 6: CONTACTS
-- ============================================================

drop policy if exists "contacts_authenticated_all" on public.contacts;

create policy "contacts_admin_all"
  on public.contacts for all
  to authenticated
  using (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  );

-- Select: own row always visible; team members in same org visible too.
-- (ClientTeam queries all contacts for the client — needs cross-contact select.)
create policy "contacts_own_client_select"
  on public.contacts for select
  to authenticated
  using (
    user_id = auth.uid()
    or client_id = public.current_user_client_id()
  );

-- Update/delete: scoped to own organisation (owner can remove/update team members)
create policy "contacts_own_client_update"
  on public.contacts for update
  to authenticated
  using  (client_id = public.current_user_client_id())
  with check (client_id = public.current_user_client_id());

create policy "contacts_own_client_delete"
  on public.contacts for delete
  to authenticated
  using (client_id = public.current_user_client_id());

-- Insert: users may only create a contact record for themselves (user_id = auth.uid()).
-- This covers both signup provisioning and invitation acceptance.
-- The client_id is controlled by application logic (provisionClientSignup uses a fresh
-- UUID; acceptPendingInvitation uses the client_id from the verified invitation row).
create policy "contacts_self_insert"
  on public.contacts for insert
  to authenticated
  with check (user_id = auth.uid());


-- ============================================================
-- STEP 7: MAP_DATA_SOURCES
-- ============================================================

drop policy if exists "map_data_sources_authenticated_all" on public.map_data_sources;

create policy "mds_admin_all"
  on public.map_data_sources for all
  to authenticated
  using (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  );

create policy "mds_own_client"
  on public.map_data_sources for all
  to authenticated
  using (
    map_id in (
      select id from public.maps where client_id = public.current_user_client_id()
    )
  )
  with check (
    map_id in (
      select id from public.maps where client_id = public.current_user_client_id()
    )
  );


-- ============================================================
-- STEP 8: INVITATIONS (no RLS existed before)
-- ============================================================

alter table public.invitations enable row level security;

create policy "invitations_admin_all"
  on public.invitations for all
  to authenticated
  using (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  );

-- Org owners/managers: read + manage invitations for their client
create policy "invitations_own_client"
  on public.invitations for all
  to authenticated
  using  (client_id = public.current_user_client_id())
  with check (client_id = public.current_user_client_id());

-- Any authenticated user can read an invitation addressed to their own email.
-- Required by acceptPendingInvitation which runs before the contact row exists.
create policy "invitations_own_email_select"
  on public.invitations for select
  to authenticated
  using (
    lower(email) = lower((select email from auth.users where id = auth.uid()))
  );

-- Users can mark their own invitation as accepted (update accepted_at).
create policy "invitations_own_email_accept"
  on public.invitations for update
  to authenticated
  using  (lower(email) = lower((select email from auth.users where id = auth.uid())))
  with check (lower(email) = lower((select email from auth.users where id = auth.uid())));


-- ============================================================
-- STEP 9: CONTACT_MAP_PERMISSIONS (no RLS existed before)
-- ============================================================

alter table public.contact_map_permissions enable row level security;

create policy "cmp_admin_all"
  on public.contact_map_permissions for all
  to authenticated
  using (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  );

-- Owners/managers: read + manage permissions for all contacts in their org
create policy "cmp_own_client"
  on public.contact_map_permissions for all
  to authenticated
  using (
    contact_id in (
      select id from public.contacts
      where client_id = public.current_user_client_id()
    )
  )
  with check (
    contact_id in (
      select id from public.contacts
      where client_id = public.current_user_client_id()
    )
  );

-- Invitation acceptance: a freshly-created contact may insert their own map permissions.
-- contact_id must belong to the currently authenticated user.
create policy "cmp_self_insert"
  on public.contact_map_permissions for insert
  to authenticated
  with check (
    contact_id in (
      select id from public.contacts where user_id = auth.uid()
    )
  );


-- ============================================================
-- STEP 10: MAP_PUBLICATIONS
-- Existing anon+authenticated select policy only shows the live
-- publication for an embed — already correct.
-- Add write policies so the dashboard publish/rollback actions
-- respect tenant boundaries (the security-definer RPCs are fixed below).
-- ============================================================

create policy "map_publications_admin_all"
  on public.map_publications for all
  to authenticated
  using (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
  );

create policy "map_publications_own_client"
  on public.map_publications for all
  to authenticated
  using (
    map_id in (
      select id from public.maps where client_id = public.current_user_client_id()
    )
  )
  with check (
    map_id in (
      select id from public.maps where client_id = public.current_user_client_id()
    )
  );


-- ============================================================
-- STEP 11: MAP_CONTACT_SUBMISSIONS
-- Tighten the broad authenticated_insert: scope preview inserts
-- to maps that belong to the authenticated user's client.
-- Anon insert (embed) already scoped to published maps.
-- ============================================================

drop policy if exists "map_contact_submissions_authenticated_insert" on public.map_contact_submissions;

create policy "map_contact_submissions_authenticated_insert"
  on public.map_contact_submissions for insert
  to authenticated
  with check (
    -- Admins can insert for any map (admin preview)
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
    or
    -- Client users can only insert for their own maps (client preview)
    map_id in (
      select id from public.maps where client_id = public.current_user_client_id()
    )
  );


-- ============================================================
-- STEP 12: Fix security-definer RPCs that skip access checks
-- publish_map and rollback_map_to are security definer, so they
-- bypass RLS entirely — they must check tenant access themselves.
-- ============================================================

create or replace function public.publish_map(
  p_map_id text,
  p_config jsonb,
  p_note text default null
)
returns public.map_publications
language plpgsql
security definer
set search_path = public
as $$
declare
  v_next_ver integer;
  v_pub      public.map_publications%rowtype;
  v_note     text;
  v_client   text;
begin
  -- Resolve the map's client
  select client_id into v_client from public.maps where id = p_map_id;
  if not found then
    raise exception 'Map not found';
  end if;

  -- Enforce access: must be admin or belong to this client
  if not (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
    or exists (select 1 from public.contacts where user_id = auth.uid() and client_id = v_client)
  ) then
    raise exception 'Access denied';
  end if;

  if coalesce((p_config->>'schemaVersion')::integer, 0) <> 1 then
    raise exception 'Invalid publication config: schemaVersion must be 1';
  end if;
  if p_config->'map' is null then
    raise exception 'Invalid publication config: missing map';
  end if;
  if p_config->'groups' is null then
    raise exception 'Invalid publication config: missing groups';
  end if;

  select coalesce(max(version), 0) + 1
    into v_next_ver
  from public.map_publications
  where map_id = p_map_id;

  v_note := nullif(trim(coalesce(p_note, '')), '');

  insert into public.map_publications (map_id, version, config, note, published_by)
  values (p_map_id, v_next_ver, p_config, v_note, auth.uid())
  returning * into v_pub;

  update public.maps
  set
    current_publication_id = v_pub.id,
    published_config       = p_config->'map',
    published_at           = v_pub.published_at
  where id = p_map_id;

  return v_pub;
end;
$$;

create or replace function public.rollback_map_to(
  p_map_id        text,
  p_publication_id uuid
)
returns public.map_publications
language plpgsql
security definer
set search_path = public
as $$
declare
  v_src      public.map_publications%rowtype;
  v_next_ver integer;
  v_pub      public.map_publications%rowtype;
  v_client   text;
begin
  select client_id into v_client from public.maps where id = p_map_id;
  if not found then
    raise exception 'Map not found';
  end if;

  if not (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
    or exists (select 1 from public.contacts where user_id = auth.uid() and client_id = v_client)
  ) then
    raise exception 'Access denied';
  end if;

  select * into v_src
  from public.map_publications
  where id = p_publication_id and map_id = p_map_id;

  if not found then
    raise exception 'Publication not found for this map';
  end if;

  select coalesce(max(version), 0) + 1
    into v_next_ver
  from public.map_publications
  where map_id = p_map_id;

  insert into public.map_publications (map_id, version, config, note, published_by)
  values (
    p_map_id,
    v_next_ver,
    v_src.config,
    format('Restore version %s', v_src.version),
    auth.uid()
  )
  returning * into v_pub;

  update public.maps
  set
    current_publication_id = v_pub.id,
    published_config       = v_pub.config->'map',
    published_at           = v_pub.published_at
  where id = p_map_id;

  return v_pub;
end;
$$;

create or replace function public.list_map_publications(p_map_id text)
returns setof public.map_publications
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_client text;
begin
  select client_id into v_client from public.maps where id = p_map_id;
  if not found then
    raise exception 'Map not found';
  end if;

  if not (
    exists (select 1 from public.profiles where user_id = auth.uid() and role = 'admin')
    or exists (select 1 from public.contacts where user_id = auth.uid() and client_id = v_client)
  ) then
    raise exception 'Access denied';
  end if;

  return query
    select * from public.map_publications
    where map_id = p_map_id
    order by version desc;
end;
$$;
